version: '3'

services:
  redis01:
    build: ./redis
    ports:
      - 26381:26379
      - 6381:6379
    networks:
      - host
    env_file:
      - './redis/env/master_variables.env'

  redis02:
    build: ./redis
    ports:
      - 26382:26379
      - 6382:6379
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - './redis/env/slave_variables.env'

  redis03:
    build: ./redis
    ports:
      - 26383:26379
      - 6383:6379
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - './redis/env/slave_variables.env'

  proxy01:
    build: ./haproxy
    depends_on:
      - redis01
      - redis02
      - redis03
    networks:
      - host
    ports:
      - '9001:9000'
      - '8081:80'
      - '7071:70'

  proxy02:
    build: ./haproxy
    depends_on:
      - redis01
      - redis02
      - redis03
    networks:
      - host
    ports:
      - '9002:9000'
      - '8082:80'
      - '7072:70'
  proxy03:
    build: ./haproxy
    depends_on:
      - redis01
      - redis02
      - redis03
    networks:
      - host
    ports:
      - '9003:9000'
      - '8083:80'
      - '7073:70'
# chaos commands
  chaos-pause-proxy01:
    image: gaiaadm/pumba
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "--log-level info --interval 60s pause --duration 1s re2:proxy01"
#  chaos-pause-proxy02:
#    image: gaiaadm/pumba
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: "--log-level info --interval 60s pause --duration 5s re2:proxy02"
#  chaos-pause-proxy03:
#    image: gaiaadm/pumba
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: "--log-level info --interval 120s pause --duration 10s re2:proxy03"
#  chaos-pause-redis01:
#    image: gaiaadm/pumba
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: "--log-level info --interval 30s pause --duration 10s re2:redis01"
#  chaos-pause-redis02:
#    image: gaiaadm/pumba
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: "--log-level info --interval 30s pause --duration 10s re2:redis02"
#  chaos-pause-redis03:
#    image: gaiaadm/pumba
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: "--log-level info --interval 30s pause --duration 10s re2:redis03"
#
#    
#  chaos-delay-proxy:
#    image: gaiaadm/pumba
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: "--log-level debug --interval 45s netem --tc-image gaiadocker/iproute2 --duration 10s delay re2:proxy01"
#  chaos-delay-redis:
#    image: gaiaadm/pumba
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: "--log-level debug --interval 45s netem --tc-image gaiadocker/iproute2 --duration 10s delay re2:proxy01"
networks:
  host:
